name: Ono Test Bash

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@latest

      - name: Run a multi-line script with a function
        run: |
          # Define a bash function
          function say_hello() {
            echo "Hello, $1"
          }

          # Use the function
          say_hello "GitHub Actions"
