name: Test CRON Schedule

on:
  workflow_dispatch:
  schedule:
    # Runs "1 minute" (see https://crontab.guru)
    - cron: '1 * * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: echo "test cron worked!"
