name: Test CRON Schedule

on:
  workflow_dispatch:
  schedule:
    # Runs "every 10th minute" (see https://crontab.guru)
    - cron: '*/10 * * * *'
jobs:
  build:
    name: Cron Schedule
    runs-on: ubuntu-latest
    steps:
      - name: Cron Test
        run: echo "test cron worked!"
