# This is a basic workflow to help you get started with Actions

name: CI Action1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  G_ENV: "Global Env"
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ShellCmds:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
      GH_REF_NAME: ${GITHUB_REF_NAME}
      GH_REF: ${GITHUB_REF}
      DEPLOY_ENV: old  # Default

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # TEMP OFF - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          # echo "$GITHUB_CONTEXT"
          echo "$GITHUB_REF_NAME"
          echo "$GITHUB_REF"
          echo "${{ github.ref_name }}"
          
      - name: Check - Eng Env (rc)
        if: ${{ startsWith(github.ref_name, 'main') }}
        run: |
          echo "DEPLOY_ENV=new" >> $GITHUB_ENV
          echo "dep: $DEPLOY_ENV"
          echo "dep2: ${{ env.DEPLOY_ENV }}"
        
      
      - name: Check env
        run: |
          echo "env=${{ env.DEPLOY_ENV }}"
          echo ${GITHUB_SHA::7}
          echo "SHORT_SHA=${{ GITHUB_SHA::7 }}" >> $GITHUB_ENV
          echo "Short_SHA1=${{ env.SHORT_SHA }}"
          echo "env.g_env= ${{ env.G_ENV }}"
          
      - name: Echo GH env var
        run: echo "Short_SHA2=${{ env.SHORT_SHA }}"
